; PlatformIO Project Configuration File}
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:main]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
src_filter = +<main.cpp>
lib_deps = 
	adafruit/Adafruit Unified Sensor
	adafruit/Adafruit BusIO
	adafruit/Adafruit BNO055
	servo
	wire


[env:test_motors]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
src_filter = +<test_motors.cpp>
lib_deps = 
	adafruit/Adafruit Unified Sensor
	adafruit/Adafruit BusIO
	adafruit/Adafruit BNO055
	servo
	wire


[env:test_kicker]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
src_filter = +<test_kicker.cpp>
lib_deps = 
	adafruit/Adafruit Unified Sensor
	adafruit/Adafruit BusIO
	adafruit/Adafruit BNO055
	servo
	wire